### PR TITLE
Update ruby to 2.2.3

### LINKED ISSUE #8: Upgrade to Ruby 2.2.3

### PR DESCRIPTION
**Pull request by sharmaansh21**
fixes #8

### CODE REVIEW

**Comment by sharmaansh21** [comment]
@subelsky

**Comment by subelsky** [comment]
@justanshulsharma thanks for the patch! Unfortunately the tests do not run in this branch, so I can't merge. The `Gemfile` also needs to be updated - when you are ready for me to merge the branch again let me know, just be sure to mention if the tests pass. Thanks!

**Comment by subelsky** [comment]
@optimisticanshul if you make that one change to the Gemfile I can merge this

**Comment by sharmaansh21** [comment]
@subelsky :+1:

**Comment by subelsky** [comment]
thanks!

**Pull request merged**
