### PR TITLE
Resolve my conflict

### PR DESCRIPTION
**Pull request by trendwithin**
Replaced local system username with `postgres` for database.yml due to conflict.

### CODE REVIEW

**Comment by trendwithin** [comment]
This is still stating I have a merge conflict after altering postgres.

**Comment by subelsky** [comment]
@trendwithin This is an easy fix but may take some digging for you to get your environment in the right state. You'll see on this page a blue link for "use the command line" which gives a hint of how to proceed. 

if you pull the latest changes from ignitebaltimore/ignitespeak into your branch, the merge conflict will go away. It's really just a 2 line fix on the README file.

Recommended reading:
- http://dont-be-afraid-to-commit.readthedocs.org/en/latest/git/conflicts.html
- https://help.github.com/articles/using-pull-requests/
- https://help.github.com/desktop/guides/contributing/syncing-your-branch/
- https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**Comment by trendwithin** [comment]
This should do it- good refresher on conflicts.  Hadn't notice the modification so quickly after my fork.  Good reminder to pay attention to changes in the master and pulling and merging before pushing as well.

**Comment by subelsky** [comment]
cc @pollygee

**Pull request merged**
