### PR TITLE
Use Docker Compose to set up the development environment

### PR DESCRIPTION
**Pull request by d2bit**
I used to develop on dockerized environments, I hope you like it. So I don't have to keep it untracked.

### CODE REVIEW

**Comment by subelsky** [comment]
I love this! Is there a way to add postgres to this image? One of the issues messing us up is I had to switch the project to `sqlite3` for development and `postgres` for production which is not ideal

**Comment by d2bit** [comment]
Of course it's possible to use any database.
I'll set postgres as default database... =)

**Comment by subelsky** [comment]
cool! We may need to modify `database.yml` to point to that database then. I'm installing Docker now to try it out!

**Comment by d2bit** [comment]
btw, what do you think about untracking `database.yml` and adding `database.yml.example` as default config and `database.yml.docker` as docker default config, and so on

**Pull request merged**
